# .github/workflows/trivy-full-scan.yml

name: Trivy Vulnerabilities + Secrets Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '21 13 * * 3'

permissions:
  contents: read
  security-events: write

jobs:
  trivy-full-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (for package scanning)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Scan for CVEs (library+OS) and secrets
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scanners: vuln,secret
          vuln-type: library,os
          input: .
          format: sarif
          output: trivy-full.sarif
          severity: CRITICAL,HIGH

      - name: Upload Trivy SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-full.sarif
