# .github/workflows/trivy-full-scan.yml

name: Trivy Vulnerabilities + Secrets Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '21 13 * * 3'

permissions:
  contents: read
  security-events: write

jobs:
  trivy-full-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (for package-lock.json → node_modules)
        uses: actions/setup-node@v3
        with:
          node-version: '18'       # or whatever version your project uses

      - name: Install dependencies
        run: |
          npm ci                   # ensures package-lock.json and node_modules exist

      - name: Scan for CVEs (library+OS) and secrets
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scanners: vuln,secret
          vuln-type: library,os     # scan both OS packages and JS libraries
          input: .                  # look at the entire repo
          format: sarif
          output: trivy-full.sarif
          severity: CRITICAL,HIGH   # only fail/report on CRITICAL/HIGH

      - name: Upload Trivy SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-full.sarif
